### ISSUE TITLE
Missed stories

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#10]
## Stories
- [x] Add `hover` state in `Select` story using className
- [x] Add `hover` state in `SelectUi` story using className
- [x] Add `hover` state in `HelperUi` story using className
- [x] Add `hover` state in `LabelUi` story using className

React / HTML Theme All States
- [x] Add `hover` state example in  `Select`
- [x] Add `hover` state example in  `SelectUi`
- [x] Add `hover` state example in  `HelperUi`
- [x] Add `hover` state example in  `LabelUi`
- [x] Fix misspelled `Disabled` word in example
http://localhost:8080/?path=/story/selectui-uncontrolled--react-theme-all-states
- [x] Sort Theme tabs to follow the examples: Default, Focus, Focus/Active, Disabled
http://localhost:8080/?path=/story/helper-ui--react-theme-all-states
http://localhost:8080/?path=/story/label-ui--react-theme-all-states

**Comment by Kosukeee** [comment]
@claudio-moya ,
Added `hover` state,
https://github.com/rakuten-rex/select/commits/develop
