### ISSUE TITLE
Match Figma colors

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#12]
Verify and update the component with latest version of Figma design specs (Colors, Width, Height, Margin/Padding, etc.) for:
- [x] Fonts/Texts
- [x] States
- [x] Icons

**Recommendation**: 
Split your screen on left side Storybook and right side Figma file to have a visual comparison.

**Comment by Kosukeee** [comment]
Fixed icon position,
https://github.com/rakuten-rex/select/commits/develop

**Comment by claudio-moya** [comment]
thanx
