### ISSUE TITLE
Add missed states

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#14]
## Component
- [x] Add Error state
- [x] Add Valid state
- [x] Add Required state

## Stories
- [x] Add Error state story
- [x] Add Valid state story
- [x] Add Required state story

**Comment by Kosukeee** [comment]
Added `required` state,
https://github.com/rakuten-rex/select/commit/60c6cfdc53fcd123198ed367673156334d32d0af

Added `error` and `valid` state,
https://github.com/rakuten-rex/select/commit/6c60a78782f3927bf01bcbd5150ea8bc02285cc3

**Comment by claudio-moya** [comment]
thanx
