### ISSUE TITLE
Error state on hover set default color 

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#15]
## Theme
- [x] Helper text should be red in hover/active state
- [x] Error state should use the same color (red) on default and hover/active state (current one on hover is blue) including Label and Helper
![select-error-state](https://user-images.githubusercontent.com/10554673/77884223-9d247480-729f-11ea-9e89-ffbaccbdda52.gif)

**Comment by Kosukeee** [comment]
I confirmed with Robby before, Error state hover/active color stays same error color.
Also keeps 1px border on active state.

(In this example error state has 2px border, in our case 1px)
![google-form](https://user-images.githubusercontent.com/6793504/77973903-89751e80-7330-11ea-8ebc-396ca08e7d24.gif)

**Comment by Kosukeee** [comment]
Fixed the issue,
https://github.com/rakuten-rex/select/commit/12fc8c0db7c6d03b2e32e5670206f7d536ea34ed

**Comment by claudio-moya** [comment]
thanx

**Comment by claudio-moya** [comment]
thanx
