### ISSUE TITLE
Valid state color issue

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#16]
## Theme
- [x] Helper text should be green in hover/active state
- [x] The out border color should be the default one (blue) on hover/active state (current one is dark gray) also triangle Icon should keep the same color (blue)
![select-valid-state](https://user-images.githubusercontent.com/10554673/77884648-6d29a100-72a0-11ea-8823-05075bf7f716.gif)

**Comment by Kosukeee** [comment]
I confirmed with Robby before, Error state hover/active color stays same error color.
Also keeps 1px border on active state.

(In this example error state has 2px border, in our case 1px)

![google-form](https://user-images.githubusercontent.com/6793504/77974042-f983a480-7330-11ea-9124-e38ae03f9a3c.gif)

**Comment by Kosukeee** [comment]
Fixed the issue,
https://github.com/rakuten-rex/select/commit/12fc8c0db7c6d03b2e32e5670206f7d536ea34ed

**Comment by claudio-moya** [comment]
thanx
