### ISSUE TITLE
Valid and Error state helper color

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#17]
- [ ] Valid and Error helper text color on active state change to gray, it should be green/red as the icon
![image](https://user-images.githubusercontent.com/10554673/77981226-458c1480-7344-11ea-85cb-f3676eda2488.png)
![image](https://user-images.githubusercontent.com/10554673/77981238-4c1a8c00-7344-11ea-8f61-7e379e79943d.png)

**Comment by Kosukeee** [comment]
Fixed the issue,
https://github.com/rakuten-rex/select/commit/4404aff6578f1c1ceb834b0516da61321755e3f6
