### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#2]
Blacklog tasks for next releases

Component
- [ ] Add max text limit on Mobile view (iPhone 5) for option length (try maybe text-overflow: ellipsis), currently overflows to right and over the option triangle (fix is optional for this release)

Theme
- [ ] Add `Font-weight` and `Icon size` as theme props

**Comment by claudio-moya** [comment]
Component
- [ ] Combine styles into one for `SelectHelper`, `SelectLabel` and `SelectLabelHelper` to avoid loading external styles for HTML, currently:
```html
<link href="https://unpkg.com/@rakuten-rex/select@latest/Select/Select.production.min.css" rel="stylesheet">
<link href="https://unpkg.com/@rakuten-rex/select@latest/HelperUi/HelperUi.production.min.css" rel="stylesheet">
```

expected:
```html
<link href="https://unpkg.com/@rakuten-rex/select@latest/SelectHelper/SelectHelper.production.min.css" rel="stylesheet">
```

**Comment by Kosukeee** [comment]
Confirm about `error` state  with Robby.

Use case : user didn't select anything and click `Send`, we need to show error state.
