### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/select#3]
Component

- [x] Remove `hooks` from state management, use component UI and Class to handle state (see checkbox as reference https://github.com/rakuten-rex/checkbox)
- [x] Add a new default prop `value` as empty string instead of hardcode `'Choose your age range'` due to that values should be provided by enduser
https://github.com/rakuten-rex/select/blob/1d8dff8a097e0b0f61fe4d2e15a88769d8f972c6/src/Select/Select.jsx#L57
- [x] Remove `rex-typography-root` className due to is not longer used
- [x] Rename `form-control` to `rex-select-native` and move the class inside of `rex-select();` sass mixin

Theme
- [x] Theme props `Font-weight` should be open to enduser instead of fixed sizes (S, M, L), see checkbox group `Margin` props as reference https://rakuten-rex.github.io/checkbox/?path=/story/checkbox-group-controlled--with-theme-react-and-css-vars
- [x] Theme is not working for `FormHelperText` and `FormInputLabel` (those components Theme setup is not correct, once is fixed it will work in this component)

**Comment by Kosukeee** [comment]
@claudio-moya ,
Fixed the issues and pushed to remote.
Thanks.

**Comment by claudio-moya** [comment]
Component
- [ ] Merge `label` and `helper` into `select` component

Theme
- [ ] Remove option for `Font-weight` (due to Icon size is not working) -> moved to https://github.com/rakuten-rex/select/issues/2

**Comment by claudio-moya** [comment]
Component
- [ ] Create new components for output different variations like `Select`, `SelectHelper`, `SelectLabel`, `SelectLabelHelper` and also the UI components `SelectUI`, `HelperUI`, `LabelUI`, use this reference:
![viber_image_2020-01-28_10-21-13](https://user-images.githubusercontent.com/10554673/73227869-4b387300-41b8-11ea-83f8-b81250cfd8f1.jpg)

**Comment by claudio-moya** [comment]
Stories
- [ ] Create `CommonProps` function to handle common Knobs, similar to this one
https://github.com/rakuten-rex/radio-button/blob/384d8e034c2bd610fc7fa9587040057e7387fdde/src/Radio/Radio.stories.jsx#L60-L76

https://github.com/rakuten-rex/radio-button/blob/master/src/Radio/props.js

**Comment by claudio-moya** [comment]
Component
- [ ]  If `htmlFor` is empty, remove the property
http://localhost:8080/?path=/story/label-ui--with-dynamic-props
- [ ] `Select` default view has empty placeholder and it triggers an Accessibility issue
http://localhost:8080/?path=/story/select-controlled--default

Theme
- [ ] `Text Color` option is not working
http://localhost:8080/?path=/story/selectui-uncontrolled--with-theme-react-and-css-vars

**Comment by claudio-moya** [comment]
Stories
- [ ] Replace `options` with values from `CommonProps` in Default View in all components

**Comment by claudio-moya** [comment]
Component & Stories
- [ ] Option values should have `Value` and `Text` for `<option value="123">My Text</option>`

**Comment by claudio-moya** [comment]
Component
- [ ] Default value for `placeholder` in `SelectUi`, `label` in `LabelUi` and `helper` in `HelperUi` should be empty string instead of default text

Stories
- [ ] Update `Default View` by adding `placeholder` in `SelectUi`, `label` in `LabelUi` and `helper` in `HelperUi` as prop

**Comment by claudio-moya** [comment]
- [ ] Use value instead of text for `key=`, try something like this (if some ESlint warning shows up, ignore it):
```jsx
options.map((option, index) => ( 
const key = `rex-select-key-${index}-${value}`;
```

https://github.com/rakuten-rex/select/blob/1ccfa6a507f0c12eb1acfb78b08eab3aa1ab879a/src/SelectUi/SelectUi.jsx#L48-L52

**Comment by claudio-moya** [comment]
Readme
- [ ] Update readme content with the latest version of components code
